### PR TITLE
Add EVREAL Poster

### PR DESCRIPTION
**Pull request by ercanburak**

### CODE REVIEW

**Comment by shiba24** [comment]
@ercanburak  it seems like there is a conflict? Could you take a look? (I don't know why there is a conflict tho..)

**Comment by ercanburak** [comment]
Hi @shiba24, I wanted to fix it now but I'm on the phone, and it does not look like there is a "real" conflict to resolve. If you are available, is it possible for you to add our poster?

**Comment by shiba24** [comment]
Yes it's somehow strange to me too. I can work on it, later in the afternoon

**Comment by shiba24** [comment]
@ercanburak hi actually i found that the index (the poster number) is different. We changed at some point. It would be great if you can rebase the latest main. Since you have pdf file in the PR too I can't complete it by myself.

**Comment by ercanburak** [comment]
Hi @shiba24, the conflict has been resolved now, can you check it?

**Comment by guillermogb** [comment]
thank you

**Pull request merged**
